Changes in support of ZK/GCC update to binder/nameservice
joyent/mname-balancer pull request #3
Opened 2020-03-12 13:13 UTC by bowrocker

With the [update](https://github.com/joyent/binder/pull/14), the GCC version is 7.4.0. This PR fixes compilation and platform errors.

Note: the dependency on libcbuf, currently in a personal repo, should be forked into the Joyent org before this PR merges.

2020-03-12 13:31 UTC, jlevon requested changes

2020-03-12 13:31 UTC, jlevon commented on Makefile
> +# Copyright (c) 2020, Joyent, Inc.
nit: the original is RFD 164 compliant, not this

2020-03-12 13:31 UTC, jlevon commented on deps/libcloop/src/cserver.c
> +			fprintf(stderr, "CCONN[%p] WRITE DATA: HAVE %ld; "
Here and generally, including libcbuf changes: these should be %zu
as size_t is unsigned, and that way we won't break 32-bit compiles.

We might also want to consider adding -m64 to the Makefiles so we're
explicit about what mode we're compiling in.

2020-03-12 15:52 UTC, jlevon submitted a review, later dismissed
Thanks. Are we going to do a separate PR for when we have joyent/libcbuf set up with those fixes too?

2020-03-12 16:27 UTC, bowrocker commented
> Thanks. Are we going to do a separate PR for when we have joyent/libcbuf set up with those fixes too?

I put the changes here for now: https://github.com/bowrocker/libcbuf/pull/1

2020-03-16 18:32 UTC, jlevon approved these changes

2020-03-19 15:31 UTC, merged